// <auto-generated />
using System;
using Blogifier.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blogifier.Infrastructure.Migrations
{
    [DbContext(typeof(BlogifierDbContext))]
    [Migration("20231023123927_BlogCategories")]
    partial class BlogCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Blogifier.Domain.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The invitation from the almighty God to walk before Him: In May 2012 in an extra-ordinary experience the Lord God woke me up from sleep asked me to open my bible to Genesis 17, verses one to eight and spoke to me a very fundamental message that I should send so that it reaches every single person on planet earth. \"Go tell my people I invite them to live their lives in My presence. To those who accept this invitation, I make five solemn promises to them. There are five things however they need to know, believe and experience\". Below are the five solemn promises and the five things you need to know, believe and experience (the needs).This message is sent to you backed by the transforming  power of the Almighty God. Understanding this message will transform your life!",
                            SubTitle = "The Daily Message",
                            Title = "The Message"
                        });
                });

            modelBuilder.Entity("Blogifier.Domain.BlogCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlogPostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.ToTable("BlogCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Faith"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hope"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Love"
                        });
                });

            modelBuilder.Entity("Blogifier.Domain.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedOnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 1,
                            Content = "In May 2012 in an extra-ordinary experience the Lord God woke me up from sleep asked me to open my bible to Genesis 17, verses one to eight and spoke to me a very fundamental message that I should send so that it reaches every single person on planet earth. \"Go tell my people I invite them to live their lives in My presence. To those who accept this invitation, I make five solemn promises to them. There are five things however they need to know, believe and experience\". Below are the five solemn promises and the five things you need to know, believe and experience (the needs).This message is sent to you backed by the transforming  power of the Almighty God. Understanding this message will transform your life!",
                            ContentType = 0,
                            Description = "&lt;p&gt;This is your scripture for today, may it empower you. Please share widely and make someone&#39;s day.“But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, Meekness, temperance: against such there is no law.”??Galatians? ?5:22-23? ?KJV??.&quot;So faith comes by hearing and hearing by  ...&lt;/p&gt;",
                            PublishedOnDate = new DateTime(2015, 9, 21, 22, 15, 0, 0, DateTimeKind.Unspecified),
                            Slug = "faith-is-a-gift-of-God",
                            Title = "Faith Is A Gift Of God"
                        });
                });

            modelBuilder.Entity("Blogifier.Domain.BlogCategory", b =>
                {
                    b.HasOne("Blogifier.Domain.BlogPost", null)
                        .WithMany("Categories")
                        .HasForeignKey("BlogPostId");
                });

            modelBuilder.Entity("Blogifier.Domain.BlogPost", b =>
                {
                    b.HasOne("Blogifier.Domain.Blog", null)
                        .WithMany("BlogPosts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blogifier.Domain.Blog", b =>
                {
                    b.Navigation("BlogPosts");
                });

            modelBuilder.Entity("Blogifier.Domain.BlogPost", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
